// <auto-generated />
using System;
using EmployeeProject.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeProject.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231106164535_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeProject.Entities.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SeniorId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("SeniorId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeProject.Entities.Models.Employee", b =>
                {
                    b.HasOne("EmployeeProject.Entities.Models.Employee", "Senior")
                        .WithMany("Juniors")
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Senior");
                });

            modelBuilder.Entity("EmployeeProject.Entities.Models.Employee", b =>
                {
                    b.Navigation("Juniors");
                });
#pragma warning restore 612, 618
        }
    }
}
